locate_drink_action_server:
  ros__parameters:
    # Target position parameters (relative to depth_camera_link_optical frame)
    target_x: 0.0        # Target horizontal position (meters) - centered in camera view
    target_z: 0.625       # Target distance from camera (meters)
    x_tolerance: 0.01   # Horizontal tolerance (meters) - success when |error_x| < x_tolerance
    z_tolerance: 0.02   # Distance tolerance (meters) - success when |error_z| < z_tolerance

    # Control parameters (proportional control gains)
    k_linear: 1.2     # Linear velocity gain (higher = faster forward/backward movement)
    k_angular: 2.0     # Angular velocity gain (higher = faster rotation)
    max_linear_vel: 0.5  # Maximum linear velocity (m/s)
    max_angular_vel: 0.5 # Maximum angular velocity (rad/s)
    min_movement_threshold: 0.001  # Minimum velocity to prevent oscillations

    # Camera parameters - SIMULATION (Gazebo)
    h_fov: 1.089         # Horizontal field of view in radians (~62.4 degrees)
    aspect_ratio: 1.333  # Aspect ratio (width/height) - 4:3
    camera_frame: 'depth_camera_link_optical'
    image_width: 640     # Image width in pixels
    image_height: 480    # Image height in pixels
    depth_sample_size: 5 # Number of pixels (NxN window) to average for depth calculation
    bbox_shift_ratio: 0.3 # Horizontal shift for depth sampling as ratio of bbox height (sim cameras are aligned, no offset needed)

    # Y-value override (for debugging/testing)
    override_y_value: true  # Enable to force Y value to fixed_y_value (disables calculated Y from depth camera)
    fixed_y_value: 0.1       # Fixed Y value (meters) when override_y_value is true

    # Operation parameters
    max_detection_attempts: 3   # Maximum number of detection attempts before failure
    control_loop_rate: 2.0      # Control loop frequency (Hz) - balance responsiveness vs API costs
    overall_timeout: 60.0       # Overall operation timeout (seconds)
    api_timeout: 10.0           # Gemini API timeout (seconds)
    movement_settle_time: 0.5   # Time to wait after sending velocity command (seconds)
