locate_drink_action_server:
  ros__parameters:
    # Target position parameters (relative to depth_camera_link_optical frame)
    target_x: 0.0        # Target horizontal position (meters) - centered in camera view
    target_z: 0.625       # Target distance from camera (meters)
    position_tolerance: 0.035  # Position tolerance (meters) - success when within this range

    # Control parameters (proportional control gains)
    k_linear: 1.1       # Linear velocity gain (higher = faster forward/backward movement)
    k_angular: 1.5     # Angular velocity gain (higher = faster rotation)
    max_linear_vel: 1.0  # Maximum linear velocity (m/s)
    max_angular_vel: 1.0 # Maximum angular velocity (rad/s)
    min_movement_threshold: 0.001  # Minimum velocity to prevent oscillations

    # Camera parameters - SIMULATION (Gazebo)
    h_fov: 1.089         # Horizontal field of view in radians (~62.4 degrees)
    aspect_ratio: 1.333  # Aspect ratio (width/height) - 4:3
    camera_frame: 'depth_camera_link_optical'
    image_width: 640     # Image width in pixels
    image_height: 480    # Image height in pixels
    depth_sample_size: 5 # Number of pixels (NxN window) to average for depth calculation

    # Operation parameters
    max_detection_attempts: 3   # Maximum number of detection attempts before failure
    control_loop_rate: 2.0      # Control loop frequency (Hz) - balance responsiveness vs API costs
    overall_timeout: 60.0       # Overall operation timeout (seconds)
    api_timeout: 10.0           # Gemini API timeout (seconds)
    movement_settle_time: 0.5   # Time to wait after sending velocity command (seconds)
