# Default initial positions for wilson's ros2_control fake system

initial_positions:
  gripper_left_finger_joint: 0
  gripper_right_finger_joint: 0
  joint_1: 0
  joint_2: 0
  joint_3: -1.57
  joint_4: 0