# Default initial positions for wilson's ros2_control fake system

initial_positions:
  end_effector_roll_joint: 0
  end_effector_yaw_joint: 0
  gripper_left_finger_joint: 0
  gripper_right_finger_joint: 0
  joint_1: 0
  joint_2: 0.2495
  joint_3: -2.1817
  joint_4: -0.6098